### ISSUE TITLE
Build and push to gh-pages with commits to master

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-style-guide#1]
See https://docs.travis-ci.com/user/deployment-v2/providers/pages/ for the current best (?) way to have travis push to gh-pages.

**Comment by bherr2** [comment]
That's what we use in the CCF-UI. Our Travis config is probably more complicated than what you need, but it is [here](https://github.com/hubmapconsortium/ccf-ui/blob/master/.travis.yml) if you are interested in how we do it.

**Comment by ngehlenborg** [comment]
Has anyone tried to use GitHub actions for that? I'd be interested in seeing that but otherwise, I am fine with using Travis.

**Comment by bherr2** [comment]
I've thought about trying it, but since we already have so many projects that use Travis, we've yet to take the time to try it out.

**Comment by bherr2** [comment]
I would definitely recommend some sort of CI for this though. Manual deployment is no fun.

**Comment by mccalluc** [comment]
Deployed with GitHub actions. (Mixed feelings about GitHub Actions overall, but this works.)
